// Photos des artistes — dans public/images/artists/
export const ARTIST_PHOTOS = {
    "Afrojack": "/images/artists/Afrojack.jpeg",
    "Amy Macdonald": "/images/artists/amy-macdonald.jpeg",
    "Arodes": "/images/artists/arodes.jpg",
    "Christophe Ma\u00e9": "/images/artists/Christophe-Mae.jpg",
    "David Guetta": "/images/artists/david-guetta.jpg",
    "Don Toliver": "/images/artists/DonToliver.jpg",
    "Fedele": "/images/artists/Fedele.jpg",
    "Feu! Chatterton": "/images/artists/feu-chatterton.jpg",
    "GIMS": "/images/artists/GIMS.jpg",
    "Ga\u00ebl Faye": "/images/artists/Gael-Faye.jpg",
    "Gorillaz": "/images/artists/Gorillaz.jpg",
    "Gunna": "/images/artists/gunna.jpg",
    "Helmut Fritz": "/images/artists/Helmut-Fritz.jpeg",
    "Jean-Louis Aubert": "/images/artists/Jean-Louis Aubert.jpeg",
    "John Legend": "/images/artists/john-legend.jpeg",
    "Julien Dor\u00e9": "/images/artists/julien-dore.jpg",
    "Katy Perry": "/images/artists/katy-perry.jpg",
    "Ken Carson": "/images/artists/ken-carson.jpg",
    "Kendji Girac": "/images/artists/kendji-girac.jpg",
    "Kraftklub": "/images/artists/Kraftklub.jpeg",
    "Lenny Kravitz": "/images/artists/lenny-kravitz.jpeg",
    "Lorde": "/images/artists/lorde.jpg",
    "Lost Frequencies": "/images/artists/lost-frequencies.jpg",
    "Louane": "/images/artists/louane.jpg",
    "M. Pokora": "/images/artists/mpokora.jpg",
    "Mark Forster": "/images/artists/mark-forster.jpeg",
    "Mika": "/images/artists/mika.jpg",
    "Moby": "/images/artists/moby.jpeg",
    "Nick Cave": "/images/artists/nickcave.jpeg",
    "Nicky Jam": "/images/artists/nicky_jam.jpeg",
    "Nina Chuba": "/images/artists/nina-chuba.jpeg",
    "Niska": "/images/artists/niska.jpg",
    "PLK": "/images/artists/PLK.jpg",
    "RAYE": "/images/artists/raye.jpeg",
    "Sean Paul": "/images/artists/SeanPaul.jpg",
    "Shimza": "/images/artists/shimza.jpg",
    "Sido": "/images/artists/sido.jpg",
    "Sting": "/images/artists/Sting.jpg",
    "Synapson": "/images/artists/synapson.jpg",
    "Teddy Swims": "/images/artists/Teddy-Swims.jpg",
    "The Cure": "/images/artists/the-cure.jpg",
    "The Hives": "/images/artists/the-hives.jpg",
    "Twenty One Pilots": "/images/artists/twenty_one_pilots.jpg",
    "Vanessa Paradis": "/images/artists/vanessa-Paradis.jpeg",
    "Vitaa": "/images/artists/VITAA.jpeg",
    "Wiz Khalifa": "/images/artists/Wiz-Khalifa.jpeg",
  };